import React from 'react';
import { Link } from 'react-router-dom';
import { Award, BarChart3, Check, FileCheck2, GraduationCap, Lightbulb, Presentation, Rocket, Sparkles, Users, WalletCards } from 'lucide-react';
import { IMG } from '../mock';
const philosophy=[['Des contenus pratiques','Chaque formation est construite autour de cas concrets, d’exercices et de situations professionnelles réelles.',FileCheck2],['Des parcours adaptables','Les modules peuvent être adaptés aux entreprises, écoles, ONG, institutions, jeunes talents ou entrepreneurs.',Sparkles],['Des résultats observables','La formation doit améliorer la posture, la méthode, la communication, l’organisation ou la performance.',BarChart3]];
const families=[['Vente & prospection','Développer les réflexes commerciaux, la relance, l’argumentaire, la négociation et le closing.',['Techniques de vente','Prospection terrain et digitale','Négociation et relance'],BarChart3],['Leadership & management','Renforcer la posture managériale, la communication, la prise de décision et la gestion d’équipe.',['Leadership opérationnel','Gestion d’équipe','Responsabilité et décision'],Users],['Prise de parole & impact','Améliorer l’aisance orale, la présence, le pitch, la clarté du message et la confiance en public.',['Pitch professionnel','Présentation orale','Gestion du stress'],Presentation],['Relation client','Professionnaliser l’accueil, la communication client, le suivi, la fidélisation et la gestion des situations difficiles.',['Accueil professionnel','Gestion des objections','Fidélisation client'],Users],['Entrepreneuriat','Aider les porteurs de projets à structurer leur idée, présenter leur offre, vendre et avancer avec méthode.',['Structuration de projet','Offre et positionnement','Pitch et lancement'],Rocket],['Insertion professionnelle','Préparer les jeunes talents au monde de l’entreprise : CV, entretien, posture, communication et confiance.',['Préparation entretien','CV et présentation','Posture professionnelle'],FileCheck2],['Finance & gestion d’argent','Sensibiliser à la gestion de l’argent, au budget, à l’épargne, au réinvestissement et aux décisions financières simples.',['Budget personnel','Épargne et priorités','Réinvestissement'],WalletCards],['Digital & outils professionnels','Former les équipes aux outils numériques utiles : organisation, communication, visibilité, gestion et productivité.',['Outils digitaux','Organisation numérique','Visibilité professionnelle'],Lightbulb]];
const formats=[['01','Atelier court','Format ciblé pour traiter un besoin précis : pitch, entretien, posture, vente, relation client ou digital.'],['02','Journée intensive','Une journée complète avec théorie utile, exercices, mises en situation et restitution.'],['03','Programme entreprise','Formation conçue pour une équipe, un service ou une organisation avec objectifs définis.'],['04','Parcours jeunes talents','Préparation à l’emploi, posture professionnelle, CV, entretien, confiance et mise en relation.']];
const progression=[['Diagnostic du besoin','Nous clarifions le public, les attentes, les difficultés rencontrées et les résultats souhaités.'],['Adaptation du programme','Nous adaptons les modules, les exemples, les exercices et les supports au contexte réel.'],['Animation & mise en situation','La formation alterne contenu, échanges, cas pratiques, simulations et exercices guidés.'],['Restitution & recommandations','MCE peut proposer une restitution, des axes de progression et une attestation selon le format.']];
export default function Academy(){return <main className="pt-[72px] rh-service academy-page">
 <section className="rh-service-hero"><div className="max-w-[1200px] mx-auto px-6 grid lg:grid-cols-2 gap-12 items-center"><div><h1>Apprendre, pratiquer et savoir agir en situation réelle.</h1><p>Un catalogue de formations professionnelles construit pour développer des compétences directement utilisables dans l’entreprise, l’entrepreneuriat et le management.</p><Link to="/contact">Choisir une formation</Link></div><img src={IMG.meeting} alt="Formation professionnelle MCE Academy"/></div></section>
 <section className="rh-detail-section"><div className="max-w-[1150px] mx-auto px-6"><RHHead tag="NOTRE PHILOSOPHIE" title="Former pour créer des réflexes professionnels, pas seulement transmettre de la théorie." text="Les formations MCE Academy sont pensées pour le terrain : situations réelles, exercices, échanges, mises en pratique et objectifs concrets. Chaque programme peut être adapté au niveau des participants, au secteur d’activité et aux résultats attendus."/><div className="rh-visual-cards">{philosophy.map(([t,d,I])=><article key={t}><div><I/></div><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
 <section className="rh-catalogue"><div className="max-w-[1200px] mx-auto px-6"><RHHead tag="CATALOGUE" title="Les grandes familles de formations MCE Academy" text="Ce catalogue peut évoluer selon les besoins des entreprises, partenaires, écoles et institutions. Chaque formation peut être proposée en format court, journée complète ou programme sur mesure."/><div>{families.map(([t,d,l,I])=><article key={t}><div><I/></div><h3>{t}</h3><p>{d}</p><ul>{l.map(x=><li key={x}>{x}</li>)}</ul><Link to="/contact">Demander cette formation →</Link></article>)}</div></div></section>
 <section className="rh-dark-manifesto"><div className="max-w-[1000px] mx-auto px-6"><span>APPROCHE PÉDAGOGIQUE</span><h2>Une formation MCE Academy doit produire un déclic, une méthode et une mise en action.</h2><p>L’objectif n’est pas de remplir une salle avec du contenu théorique. L’objectif est de permettre aux participants de repartir avec une meilleure posture, des outils simples, des réflexes professionnels et une progression visible.</p>{['Des programmes adaptés au niveau réel des participants.','Des exercices pratiques et des mises en situation concrètes.','Des supports de formation clairs, exploitables et professionnels.','Une logique de certificat ou d’attestation possible selon le format choisi.'].map(x=><b key={x}><Check/>{x}</b>)}</div></section>
 <section className="academy-formats-section"><div className="academy-formats-inner"><RHHead tag="FORMATS POSSIBLES" title="Des formats adaptés à vos objectifs et à votre public" text="Les formations MCE Academy peuvent être proposées aux entreprises, écoles, ONG, institutions, jeunes talents ou entrepreneurs selon plusieurs formats."/><div className="academy-formats-grid">{formats.map(([n,t,d],i)=><article key={n} className={`academy-format-card academy-format-${i+1}`}><div className="academy-format-number"><span>{n}</span><small>{i === 0 ? 'FORMAT CIBLÉ' : i === 1 ? 'FORMAT INTENSIF' : i === 2 ? 'FORMAT SUR MESURE' : 'FORMAT PARCOURS'}</small></div><div className="academy-format-copy"><h3>{t}</h3><p>{d}</p></div><i aria-hidden="true">{['↗','✦','◎','→'][i]}</i></article>)}</div></div></section>
 <section className="rh-timeline"><div className="max-w-[950px] mx-auto px-6"><RHHead tag="MÉTHODE MCE ACADEMY" title="Une progression claire, de l’analyse du besoin à la mise en pratique" text="Chaque formation peut être préparée avec une logique simple : comprendre le besoin, adapter le contenu, animer avec impact et favoriser l’application après la session."/><div>{progression.map(([t,d],i)=><article key={t}><span>{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
</main>}
function RHHead({tag,title,text}){return <header className="rh-head"><span>{tag}</span><h2>{title}</h2>{text&&<p>{text}</p>}</header>}
