import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, Compass, Globe2, Layers3, LineChart, MessageCircle, Network, Target, Users } from 'lucide-react';
import MobileCarouselControls from '../components/MobileCarouselControls';

const axes=[['Structuration de projet','Clarifier l’idée, l’offre, la cible, les priorités, les étapes et les besoins réels.',['Vision et objectifs','Offre et positionnement','Plan d’action priorisé'],Target],['Stratégie commerciale','Construire une méthode pour attirer, convaincre, vendre, relancer et fidéliser.',['Cible et prospection','Argumentaire de vente','Suivi client et relance'],LineChart],['Transformation digitale','Identifier les outils utiles : site, Landing Page, plateforme, SaaS, formulaire, CRM ou automatisation.',['Choix des outils','Organisation digitale','Parcours client'],Layers3],['Organisation interne','Mettre de l’ordre dans les rôles, les process, les documents, les responsabilités et le suivi.',['Process simples','Suivi des actions','Outils de pilotage'],Users],['Partenariats & réseau','Développer les opportunités, partenariats, rencontres professionnelles et mises en relation.',['Stratégie partenariale','Mise en relation','Opportunités business'],Network],['Suivi & progression','Accompagner la mise en œuvre, vérifier les avancées, ajuster les priorités et garder le cap.',['Points de suivi','Ajustements','Mesure des progrès'],Check]];
const formats=[['Diagnostic stratégique','Pour faire le point sur votre situation, identifier les blocages et prioriser les prochaines actions.','Analyse · Priorités · Recommandations · Plan rapide'],['Structuration de projet','Pour transformer une idée ou une activité dispersée en projet clair, organisé et présentable.','Offre · Cible · Positionnement · Organisation'],['Accompagnement commercial','Pour développer la prospection, la vente, la relance, la posture client et le suivi commercial.','Vente · Prospection · Argumentaire · Relance'],['Transformation digitale','Pour choisir les bons outils numériques et mettre en place une présence digitale cohérente.','Site web · SaaS · Formulaires · Automatisation']];
const method=[['Diagnostic','Nous analysons votre activité, vos objectifs, vos freins, votre marché et vos ressources disponibles.'],['Clarification','Nous remettons de l’ordre dans votre offre, vos priorités, votre cible et votre positionnement.'],['Plan d’action','Nous définissons les actions à mener : digital, commercial, organisation, communication ou partenariats.'],['Suivi','Selon le besoin, MCE peut accompagner l’exécution, les ajustements et les prochaines décisions.']];
export default function AccompagnementStrategique(){return <main className="pt-[72px] strategy-page">
 <section className="strategy-hero"><div className="max-w-[1200px] mx-auto px-6 grid lg:grid-cols-2 gap-12 items-center"><div><h1>Structurer, digitaliser et développer votre activité <em>avec méthode.</em></h1><p>MCE accompagne les entrepreneurs, PME, ONG, institutions et porteurs de projets dans la clarification de leur offre, leur organisation, leur stratégie commerciale, leur transformation digitale et leur développement business.</p><div><Link to="/contact" className="btn-primary rounded-full">Demander un accompagnement</Link><a href="https://wa.me/221771234567" className="strategy-whatsapp"><MessageCircle/> Échanger sur WhatsApp</a></div></div><div className="strategy-steps-visual">{['Clarifier','Structurer','Développer'].map((x,i)=><article key={x}><span/><b>{x}</b><small/></article>)}<i>Plan d’action</i></div></div></section>
 <section className="strategy-vision"><div className="max-w-[1100px] mx-auto px-6"><StrategyHead tag="NOTRE VISION" title="Un projet solide ne repose pas seulement sur une idée, mais sur une méthode" text="Beaucoup d’entrepreneurs et d’organisations ont de bonnes idées, mais avancent sans structure claire : offre floue, priorités dispersées, outils mal choisis, communication irrégulière ou stratégie commerciale insuffisamment cadrée. MCE intervient pour remettre de l’ordre, clarifier les décisions et construire un plan d’action exploitable."/><div>{[['Clarifier','Identifier ce qui bloque, ce qui manque, ce qui doit être priorisé et ce qui peut réellement créer de la valeur.'],['Structurer','Organiser l’offre, les actions, les outils, les rôles et les étapes pour rendre le projet plus lisible.'],['Développer','Transformer la stratégie en actions concrètes : visibilité, prospection, digital, partenariats et suivi.']].map(([t,d])=><article key={t}><Compass/><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
 <section className="strategy-manifesto"><div className="max-w-[1050px] mx-auto px-6"><h2>Nous ne vendons pas des conseils théoriques. Nous construisons un chemin d’action.</h2><p>L’accompagnement MCE aide à passer d’un projet dispersé à une vision claire : ce qu’il faut faire, dans quel ordre, avec quels outils, quelles priorités et quels objectifs.</p>{['Un diagnostic réaliste de votre situation actuelle.','Une stratégie adaptée à votre budget, votre niveau et votre marché.','Un plan d’action concret pour avancer sans se disperser.'].map(x=><b key={x}><Check/>{x}</b>)}</div></section>
 <section className="strategy-axes"><div className="max-w-[1200px] mx-auto px-6"><StrategyHead tag="NOS AXES D’ACCOMPAGNEMENT" title="Un accompagnement business, digital et organisationnel" text="MCE intervient sur les points essentiels qui permettent à une activité de se structurer, se rendre visible, mieux vendre, mieux s’organiser et préparer sa croissance."/><div>{axes.map(([t,d,l,I])=><article key={t}><I/><h3>{t}</h3><p>{d}</p><ul>{l.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></div></section>
 <section className="strategy-formats"><div className="max-w-[1100px] mx-auto px-6"><StrategyHead tag="FORMATS POSSIBLES" title="Un accompagnement adapté au niveau de maturité de votre projet" text="L’accompagnement peut être ponctuel ou plus complet selon le besoin : diagnostic, cadrage, stratégie, plan d’action ou suivi dans la durée."/><div id="strategy-formats-carousel">{formats.map(([t,d,c])=><article key={t}><h3>{t}</h3><p>{d}</p><small>{c}</small></article>)}</div><MobileCarouselControls targetId="strategy-formats-carousel"/></div></section>
 <section className="strategy-method"><div className="max-w-[950px] mx-auto px-6"><StrategyHead tag="MÉTHODE MCE" title="Une progression claire, du diagnostic à la mise en œuvre" text="Notre méthode permet de sortir du flou, de hiérarchiser les décisions et de transformer une intention en étapes concrètes."/><div>{method.map(([t,d],i)=><article key={t}><span>{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
 <section className="strategy-audience"><div className="max-w-[1100px] mx-auto px-6"><StrategyHead tag="POUR QUI ?" title="Un accompagnement pour les structures qui veulent passer un cap" text="MCE accompagne les projets qui ont besoin de clarté, de méthode, d’outils adaptés, de visibilité ou d’un meilleur développement commercial."/><div id="strategy-audience-carousel">{[['Entrepreneurs','Pour clarifier une idée, structurer une offre, lancer une activité ou préparer un développement.'],['PME & TPE','Pour améliorer l’organisation, la visibilité, les outils, la vente et la relation client.'],['ONG & institutions','Pour structurer un programme, digitaliser des processus ou organiser les actions terrain.'],['Diaspora & projets internationaux','Pour structurer un projet entre la France, le Maroc, le Sénégal ou l’Afrique de l’Ouest.']].map(([t,d])=><article key={t}><Globe2/><h3>{t}</h3><p>{d}</p></article>)}</div><MobileCarouselControls targetId="strategy-audience-carousel"/></div></section>
</main>}
function StrategyHead({tag,title,text}){return <header className="strategy-head"><span>{tag}</span><h2>{title}</h2><p>{text}</p></header>}
