import React from 'react';
import { Link } from 'react-router-dom';
import { ArrowRight, Check, Eye, FileText, Megaphone, Palette, Share2, Sparkles, Target, Users } from 'lucide-react';
import MobileCarouselControls from '../components/MobileCarouselControls';

const expertise = [
  ['Identité visuelle','Créer ou renforcer les éléments qui rendent votre marque reconnaissable et professionnelle.',['Logo et déclinaisons','Charte graphique','Couleurs, typographies, univers visuel'],Palette],
  ['Supports professionnels','Concevoir des documents clairs pour présenter votre activité, vendre ou convaincre.',['Plaquettes, dossiers, PDF','Présentations Canva ou PowerPoint','Flyers, affiches, cartes, catalogues'],FileText],
  ['Stratégie digitale','Définir comment votre marque doit communiquer en ligne selon sa cible et ses objectifs.',['Canaux et priorités','Messages clés','Plan d’action digital'],Target],
  ['Réseaux sociaux sur devis','Accompagner la présence sociale selon les plateformes, le volume de contenu et les objectifs.',['Calendrier éditorial','Visuels et contenus','Communication événementielle'],Share2],
  ['Publicité digitale sur devis','Préparer ou piloter des campagnes selon le budget média, la durée et le niveau de suivi attendu.',['Meta Ads','Google Ads','Campagnes de lancement'],Megaphone],
  ['Cohérence globale','Aligner votre logo, votre site, vos réseaux, vos supports et votre discours commercial.',['Message de marque','Parcours client','Alignement des supports'],Sparkles],
];
const offers=[['Pack image de marque','Pour créer ou améliorer l’identité visuelle d’une entreprise, d’un projet ou d’une marque.','Logo · Charte · Univers visuel · Déclinaisons'],['Supports professionnels','Pour disposer de documents propres, crédibles et exploitables lors de rendez-vous, événements ou partenariats.','Plaquette · Présentation · PDF · Catalogue'],['Stratégie digitale','Pour définir comment communiquer, où publier, quoi dire, à qui s’adresser et comment générer des demandes.','Canaux · Messages · Contenus · Plan d’action'],['Réseaux sociaux & campagnes','Pour gérer ou préparer une communication digitale adaptée aux objectifs, au budget et au rythme de l’entreprise.','Réseaux sociaux · Meta Ads · Google Ads · Suivi']];
const method=[['Analyse du besoin','Nous clarifions votre activité, votre cible, votre image actuelle, vos supports et vos objectifs.'],['Direction créative','Nous définissons l’univers visuel, le ton, les références, les couleurs et la cohérence globale.'],['Création des supports','Nous concevons les éléments nécessaires : identité, documents, visuels, contenus ou supports digitaux.'],['Stratégie & diffusion','Nous pouvons accompagner la mise en place d’une stratégie digitale, d’un calendrier ou d’une campagne sur devis.']];

export default function ImageMarqueStrategie(){return <main className="pt-[72px] brand-page">
  <section className="brand-hero"><div className="max-w-[1200px] mx-auto px-6 grid lg:grid-cols-2 gap-12 items-center"><div><h1>Une marque cohérente, reconnaissable et prête à convaincre.</h1><p>MCE aligne votre identité visuelle, vos supports, votre message commercial et votre présence digitale pour construire une image professionnelle, lisible et adaptée à votre cible.</p><Link to="/contact" className="btn-primary rounded-full mt-7">Construire mon image <ArrowRight className="w-4 h-4"/></Link></div><div className="brand-prism" aria-hidden="true"><span>IDENTITÉ</span><span>MESSAGE</span><span>VISIBILITÉ</span><div><Palette/></div></div></div></section>
  <section className="brand-vision"><div className="max-w-[1200px] mx-auto px-6"><BrandHead tag="NOTRE VISION" title="Une marque forte commence par un message clair" text="Une entreprise peut avoir une bonne offre mais perdre en crédibilité si son image, ses supports, son discours et sa présence digitale ne sont pas cohérents. MCE vous aide à construire une image professionnelle, lisible et adaptée à votre cible."/><div className="brand-triad">{[['Être reconnaissable','Construire une identité visuelle claire, identifiable et cohérente sur tous vos supports.',Eye],['Rassurer','Présenter une image professionnelle qui donne confiance aux clients, partenaires et institutions.',Check],['Être visible','Choisir les bons canaux, les bons messages et les bons supports pour toucher la bonne audience.',Target]].map(([t,d,I])=><article key={t}><I/><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="brand-manifesto"><div className="max-w-[1100px] mx-auto px-6"><span>APPROCHE MCE</span><h2>Votre logo, votre site, vos réseaux et vos documents doivent raconter la même histoire.</h2><p>MCE ne traite pas l’identité visuelle comme un élément isolé. L’objectif est d’aligner votre image, vos supports, votre message commercial et votre stratégie digitale pour créer une présence cohérente.</p>{['Une image professionnelle cohérente avec votre positionnement.','Des supports utiles pour présenter, vendre, convaincre ou rassurer.','Une stratégie digitale sur devis selon vos objectifs, vos canaux et vos moyens.'].map(x=><b key={x}><Check/>{x}</b>)}</div></section>
  <section className="brand-expertise"><div className="max-w-[1200px] mx-auto px-6"><BrandHead tag="NOS EXPERTISES" title="Image, supports, stratégie digitale et visibilité" text="Cette solution regroupe tout ce qui permet à votre structure d’être mieux présentée, mieux comprise, plus crédible et plus visible auprès de sa cible."/><div className="brand-expertise-grid">{expertise.map(([t,d,list,I])=><article key={t}><I/><h3>{t}</h3><p>{d}</p><ul>{list.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></div></section>
  <section className="brand-offers"><div className="max-w-[1100px] mx-auto px-6"><BrandHead tag="OFFRES SUR DEVIS" title="Chaque projet est évalué selon le besoin réel" text="Les prestations liées à l’image, aux supports, aux réseaux sociaux et à la stratégie digitale sont proposées sur devis, selon le volume, la complexité, les délais et le niveau d’accompagnement attendu."/><div id="brand-offers-carousel">{offers.map(([t,d,c])=><article key={t}><span>SUR DEVIS</span><h3>{t}</h3><p>{d}</p><small>{c}</small></article>)}</div><MobileCarouselControls targetId="brand-offers-carousel"/></div></section>
  <section className="brand-method"><div className="max-w-[1000px] mx-auto px-6"><BrandHead tag="MÉTHODE MCE" title="Une méthode claire pour construire une image cohérente" text="Avant de créer un logo, une plaquette ou une stratégie digitale, MCE cherche d’abord à comprendre votre activité, votre cible, votre positionnement et vos objectifs."/><div>{method.map(([t,d],i)=><article key={t}><span>{i+1}</span><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
  <section className="brand-audience"><div className="max-w-[1100px] mx-auto px-6"><BrandHead tag="POUR QUI ?" title="Pour les structures qui veulent mieux présenter leur valeur" text="Cette solution s’adresse aux entreprises, entrepreneurs, ONG, institutions, artisans, commerçants et porteurs de projets qui veulent professionnaliser leur image et leur communication."/><div id="brand-audience-carousel">{[['Entrepreneurs','Pour construire une image crédible dès le lancement d’une activité ou d’un projet.'],['PME & TPE','Pour améliorer l’image, les supports commerciaux et la visibilité digitale.'],['ONG & institutions','Pour créer des supports professionnels, dossiers de présentation ou documents partenaires.'],['Événements & partenariats','Pour préparer une communication claire avant un lancement, une conférence ou une opération terrain.']].map(([t,d])=><article key={t}><Users/><h3>{t}</h3><p>{d}</p></article>)}</div><MobileCarouselControls targetId="brand-audience-carousel"/></div></section>
</main>}
function BrandHead({tag,title,text}){return <header className="brand-head"><span>{tag}</span><h2>{title}</h2><p>{text}</p></header>}
