import React from 'react';
import { Link } from 'react-router-dom';
import { Check, FileCheck2, Search, Star, UserCheck, UsersRound } from 'lucide-react';
import { IMG } from '../mock';
const role=[['Clarifier le besoin réel','Définir le poste, le niveau, les missions, les priorités et le type de personnalité attendu.',FileCheck2],['Identifier les bons profils','Présélectionner les candidatures pertinentes et éviter les profils qui ne correspondent pas au contexte.',Search],['Accompagner l’intégration','Prévoir un suivi après la mise en relation pour sécuriser les premiers pas dans l’organisation.',UserCheck]];
const services=[['Définition du besoin',['Analyse du poste','Fiche de mission','Critères de sélection']],['Recherche & présélection',['Recherche de candidats','Tri des candidatures','Premier échange candidat']],['Entretiens & évaluation',['Entretien de présélection','Analyse de posture','Compte rendu candidat']],['Placement de profils',['Mise en relation','Transmission des profils','Coordination des échanges']],['Préparation des candidats',['Préparation entretien','Pitch professionnel','Conseils CV et posture']],['Suivi post-recrutement',['Point d’intégration','Feedback entreprise','Ajustements si nécessaire']]];
const method=[['Compréhension du besoin','Nous échangeons avec l’entreprise pour comprendre le poste, les missions, les contraintes et le profil attendu.'],['Recherche et présélection','Nous identifions les profils les plus cohérents et réalisons un premier niveau de tri.'],['Entretien et qualification','Nous évaluons la motivation, la posture, la compréhension du poste et la cohérence du parcours.'],['Transmission des profils','L’entreprise reçoit les profils retenus avec les informations utiles pour décider.'],['Suivi après mise en relation','MCE peut assurer un suivi après la mise en relation afin d’accompagner l’intégration.']];
const profiles=[['Commerciaux & vente','Profils terrain, conseillers, agents commerciaux, chargés de clientèle et responsables commerciaux.'],['Digital & web','Développeurs juniors, webmasters, assistants digitaux, profils WordPress, support web ou outils numériques.'],['Administratif & coordination','Assistants, coordinateurs, profils organisationnels, suivi administratif, accueil et gestion interne.'],['Communication & événementiel','Chargés de communication, assistants événementiels, community managers et profils opérationnels terrain.']];
export default function RecrutementRH(){return <main className="pt-[72px] rh-service recruitment-page"><section className="rh-service-hero"><div className="max-w-[1200px] mx-auto px-6 grid lg:grid-cols-2 gap-12 items-center"><div><h1>Trouver le bon profil, avec une méthode claire.</h1><p>MCE accompagne les PME, entreprises, ONG et organisations dans la recherche, l’évaluation et l’intégration de candidats adaptés au poste et à la réalité de la structure.</p><Link to="/contact">Confier un recrutement à MCE</Link></div><img src={IMG.team1} alt="Entretien de recrutement"/></div></section>
 <section className="rh-detail-section"><div className="max-w-[1100px] mx-auto px-6"><RHHead tag="NOTRE RÔLE" title="Recruter ne consiste pas seulement à recevoir des CV." text="Un bon recrutement commence par une compréhension claire du besoin, du contexte de l’entreprise, du niveau attendu, de la posture recherchée et de la capacité du profil à s’intégrer durablement. MCE agit comme un relais entre les organisations qui recrutent et les talents à potentiel."/><div className="rh-visual-cards">{role.map(([t,d,I])=><article key={t}><div><I/></div><h3>{t}</h3><p>{d}</p></article>)}</div></div></section>
 <section className="rh-services-grid"><div className="max-w-[1100px] mx-auto px-6"><RHHead tag="NOS SERVICES" title="Une offre complète autour du recrutement et du placement" text="MCE peut intervenir sur une mission ponctuelle, un besoin urgent, une campagne de recrutement, une présélection de profils ou un dispositif plus large autour de l’emploi et des jeunes talents."/><div>{services.map(([t,l])=><article key={t}><h3>{t}</h3><p>Une étape cadrée selon le poste, le niveau attendu et le contexte de l’organisation.</p><ul>{l.map(x=><li key={x}>{x}</li>)}</ul></article>)}</div></div></section>
 <section className="rh-dark-manifesto"><div className="max-w-[1000px] mx-auto px-6"><span>APPROCHE MCE</span><h2>Nous cherchons l’adéquation entre le besoin de l’entreprise, le potentiel du candidat et la réalité du terrain.</h2><p>Le bon profil n’est pas seulement celui qui a les compétences techniques. C’est aussi celui qui comprend l’environnement, adopte une posture professionnelle, sait apprendre, s’intégrer et évoluer dans le cadre proposé.</p>{['Une lecture humaine et professionnelle des profils.','Une attention particulière portée à la posture, la motivation et l’adaptabilité.','Une mise en relation pensée pour être utile aux entreprises et aux candidats.','Une logique de suivi pour sécuriser l’intégration après le recrutement.'].map(x=><b key={x}><Check/>{x}</b>)}</div></section>
 <section className="rh-timeline"><div className="max-w-[950px] mx-auto px-6"><RHHead tag="MÉTHODE" title="Une méthode de recrutement simple, claire et progressive" text="MCE structure le processus pour éviter les recrutements flous, les pertes de temps et les profils mal orientés."/><div>{method.map(([t,d],i)=><article key={t}><span>{i+1}</span><div><h3>{t}</h3><p>{d}</p></div></article>)}</div></div></section>
 <section className="recruit-testimonials"><div className="max-w-[1120px] mx-auto px-6"><RHHead tag="RETOURS D’EXPÉRIENCE" title="Ils témoignent de l’accompagnement MCE" text="Des retours qui mettent en avant la clarté du processus, la qualité des profils et le suivi après la mise en relation."/><div>{[['« MCE a clarifié notre besoin avant même de lancer la recherche. Les profils reçus étaient cohérents avec notre organisation. »','Direction RH','PME digitale','DR'],['« La présélection nous a fait gagner du temps et nous a permis de concentrer les entretiens sur les candidatures les plus pertinentes. »','Direction générale','Structure de services','DG'],['« Le suivi après la mise en relation a facilité l’intégration et permis d’ajuster rapidement les attentes du poste. »','Responsable d’équipe','Organisation partenaire','RE']].map(([q,n,r,i])=><article key={q}><div>{[1,2,3,4,5].map(x=><Star key={x}/>)}</div><blockquote>{q}</blockquote><footer><span>{i}</span><p><b>{n}</b><small>{r}</small></p></footer></article>)}</div></div></section>
 <section className="rh-profile-section"><div className="max-w-[1100px] mx-auto px-6"><RHHead tag="PROFILS CONCERNÉS" title="Des profils adaptés aux besoins des PME, ONG, écoles, institutions et projets digitaux" text="MCE peut accompagner des recrutements dans plusieurs domaines selon les besoins réels des structures."/><div>{profiles.map(([t,d])=><article key={t}><UsersRound/><h3>{t}</h3><p>{d}</p></article>)}</div><aside><h2>Vous cherchez un profil ou souhaitez structurer votre recrutement ?</h2><p>Présentez-nous votre besoin : poste, missions, niveau attendu, urgence, budget et contexte.</p><Link to="/contact">Demander une proposition</Link></aside></div></section>
</main>}
function RHHead({tag,title,text}){return <header className="rh-head"><span>{tag}</span><h2>{title}</h2>{text&&<p>{text}</p>}</header>}
